### ISSUE TITLE
dont work website

### ISSUE THREAD

**Issue by SUppL7** [bradenr402/fakebook#1]
Hi, mu dear. Im from TheOdin,have u email? i have any question for you)

**Comment by bradenr402** [comment]
Hello! Thank you for your interest in my application. I would like to inform you that the app is temporarily unavailable and will be made available again in due course. If you have any other questions, I would be happy to help.

___

If you would like to try out the application on your own machine, please follow the steps below:
1. Open your terminal and navigate to your preferred directory for cloning the project.

2. Execute the following command to clone the repository:
```shell
git clone https://github.com/bradenr402/fakebook.git
```

3. Change directory to the cloned repository:
```shell
cd fakebook
```

4. Install dependencies:
```shell
bundle install
```

5. Create the database:
```shell
rails db:create
```

6. Migrate the database:
```shell
rails db:migrate
```

7. Start up the application:
```shell
bin/dev
```

8. Access the application by navigating to [https://localhost:3000](https://localhost:3000) in your web browser.
